included:
  - ../GitHubKit

excluded:
  - Pods

analyzer_rules:
  - unused_import
  - unused_private_declaration

disabled_rules:
  - trailing_comma

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

identifier_name:
  excluded:
      - id
      - nl

number_separator:
  minimum_length: 5

file_name:
  excluded:
    - GitHubService+Authorization.swift
    - GitHubService+Follower.swift
    - GitHubService+GitData.swift
    - GitHubService+Misc.swift
    - GitHubService+Repository.swift
    - GitHubService+Search.swift
    - GitHubService+Showcase.swift
    - GitHubService+UserProfile.swift
    - TrendingRepository.swift
    - TrendingDeveloper.swift
    - ParseMarkdown.swift

severity: error

custom_rules:
  decode_optional_if_present:                      # rule identifier
    included: ".*\\.swift"                         # regex that defines paths to include during linting. optional.
    name: "Decode Optional If Present"             # rule name. optional.
    regex: "try container.decode\\(\\w+\\?\\.self" # matching pattern
    message: "Use `decodeIfPresent`"               # violation message. optional.
    severity: warning                              # violation severity. optional.
