use_frameworks!
platform :ios, '10.0'

target 'GitHubKit_Example' do

  pod 'SwiftLint'

  pod 'GitHubKit', :path => '../'

  inhibit_all_warnings!

  target 'GitHubKit_Tests' do
    inherit! :search_paths

    pod 'GitHubKit', :path => '../'

    jacKitPath     = '/Users/mudox/Develop/Apple/Frameworks/JacKit'
    pod 'JacKit',    :path => jacKitPath

    # BDD
    pod 'Quick'
    pod 'Nimble'

    # Testing RxSwift code
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'RxNimble'

    # Requests stubbing
    pod 'OHHTTPStubs/Swift'
  end
end
