platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'Demo' do

  pod 'SwiftLint'

  pod 'GitHubKit', :path => '../'

  target 'Tests' do
    inherit! :search_paths

    if ENV['MDX_CI'] == 'YES'
      pod 'JacKit',  :git  => 'https://github.com/mudox/jac-kit.git'
    else
      pod 'JacKit',  :path => '/Users/mudox/Develop/Apple/Frameworks/JacKit'
    end

    pod 'GitHubKit', :path => '../'

    # BDD
    pod 'Quick'
    pod 'Nimble'

    # Testing RxSwift code
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'RxNimble'

    # Requests stubbing
    pod 'OHHTTPStubs/Swift'
  end
end
